branches:
  only:
    - casperjs
before_script:
 - cd ..
 - git clone git://github.com/n1k0/casperjs.git
 - cd casperjs
 - git checkout tags/1.0.0
 - cd ../todomvc
 - export casperjs=../casperjs/bin/casperjs

script:
 - ./test.rb